### ISSUE TITLE
关于代码运行的问题

### ISSUE THREAD

**Issue by zzwDL** [hasakiXie123/FedCMR#1]
您好，我在运行代码的时候出现了一些问题：1.使用GPU会出现nan值，用CPU训练就正常运行，环境是按requirements.txt配置的。2.模型.to(device)时加载时间很久。显卡跑其他的代码都没什么问题，所以应该不是显卡的问题，我猜测可能是环境配置的问题，但是查了很久也没解决。

**Comment by hasakiXie123** [comment]
你好，我有一些问题也许可以帮助你自查。
1.PySyft库是否为0.2.9版本？
2.GPU显存是否足够？
3.输入是否存在Nan值？

**Comment by hasakiXie123** [comment]
无后续回复
